------------EJERICICIO 3-----------------------------
---TABLA LOGS----
  CREATE TABLE LOGS(
  CODIGO NUMBER PRIMARY KEY,
  DESCRIPCION VARCHAR2(800),
  FECHA TIMESTAMP, 
  USUARIO VARCHAR2(50),
  OPERACION VARCHAR2(50));
  
---------SECUENCIA QUE INCREMENTA EL ID DE PROVEEDOR----------
  
CREATE SEQUENCE SQ_TABLA_PROVEEDORES
--VALOR INICIO--
START WITH 121
--VALOR DE INCREMENTO
INCREMENT BY 1; 



--PARA UTILIZAR ESTO ANTES SE NECESITA HAVER USADO LA NEXTVAL ES DECIR ELISNER INTO
DECLARE
 VALOR_ACTUAL_SQ NUMBER;
 
BEGIN
 VALOR_ACTUAL_SQ:=SQ_TABLA_PROVEEDORES.CURRVAL;
 DBMS_OUTPUT.PUT_LINE('ACTUAL ES: '||VALOR_ACTUAL_SQ); 
 COMMIT;
END;


-----------------INCREMENTA LA TABLA LOGS EN LA LLAVE PRIMARIA -------------------
CREATE SEQUENCE SQ_LOGS
--VALOR INICIO--
START WITH 1
--VALOR DE INCREMENTO
INCREMENT BY 1; 

------------------










--------TRIGUER. NO RECIBE PARAMETROS  ----------
---- 2 VARIABLES NEW INSERT UPDATE  OBTIENE VLORES A INSERTAR A MODIFICAS 
-----OLD UPDATE DELETE ELEIMINARON O SE MODIFICARON

 CREATE OR REPLACE TRIGGER TG_PROVEEDORES
AFTER INSERT OR UPDATE OR DELETE ON PROVEEDORES
FOR EACH ROW 
DECLARE  
PRAGMA AUTONOMOUS_TRANSACTION; 
BEGIN 
IF(INSERTING) THEN 
  INSERT INTO  LOGS VALUES (SQ_LOGS.NEXTVAL, 'SE REALIZO UNA INSERT NUEVO PROVEEDOR :'||:NEW.PROVEEDORID||'NOMBRE 
  PROVEEDOR:'||:NEW.NOMBREPROV, SYSTIMESTAMP, USER, 'INSERT'
  ); 
  END IF;
  
  
IF(UPDATING)THEN 
     INSERT INTO  LOGS VALUES (SQ_LOGS.NEXTVAL, 'SE REALIZO UNA UPDATE EL ANTIGUO ES:'||:OLD.NOMBREPROV||'NUEVO
  PROVEEDOR:'||:NEW.NOMBREPROV, SYSTIMESTAMP, USER, 'UPDATE'); 
  END IF;
  
  IF(DELETING)THEN 
     INSERT INTO  LOGS VALUES (SQ_LOGS.NEXTVAL, 'SE REALIZO UNA DELETE EL ID ES:'||:NEW.PROVEEDORID||'NOMBRE 
     ERA :'||:OLD.NOMBREPROV, SYSTIMESTAMP, USER, 'DELETE');
  END IF;
   COMMIT;
  
  EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
  
END;
---BLOQUE ANONIMO.------------
BEGIN

INSERT INTO PROVEEDORES (PROVEEDORID,NOMBREPROV, CONTACTO) VALUES (SQ_TABLA_PROVEEDORES.NEXTVAL,'JUAN ANTONIO GALVES', '33315614');
COMMIT;

END;
-----UPDATE
BEGIN

UPDATE  PROVEEDORES SET NOMBREPROV='JUAN ANTONIO GALVES' WHERE NOMBREPROV='MACIAS MARCIAL ANTONIO';
COMMIT;

END;
----DELETE
BEGIN

DELETE FROM PROVEEDORES WHERE NOMBREPROV ='JUAN ANTONIO GALVES' ;
COMMIT;

END;
